Done task 1
CalvinLezes/C_Sharp pull request #1
Opened 2022-10-08 07:41 UTC by CalvinLezes

2022-10-09 04:58 UTC, Ningyo requested changes

2022-10-09 04:58 UTC, Ningyo commented on C_Sharp/Contender.cs
> +        public int Score { get => score; set => score = value; }
можно написать просто проперти без лишних приватных полей

2022-10-09 04:58 UTC, Ningyo commented on C_Sharp/Contender.cs
> +        public string? Name { get => name; set => name = value; }
думаю, имя претендента напротив должно быть обязательным. в каком случае у нас может появиться безымянный претендент?

2022-10-09 04:58 UTC, Ningyo commented on C_Sharp/Friend.cs
> +        public bool Cmp(Contender current, List<Contender> visited)
сокращения - зло

2022-10-09 04:58 UTC, Ningyo commented on C_Sharp/Friend.cs
> +            foreach(var previous in visited)
не обязательно проходиться "вручную" по списку, можно использовать стандартные методы для работы с коллекциями для фильтрации\поиска

2022-10-09 04:58 UTC, Ningyo commented on C_Sharp/Friend.cs
> +        public bool Cmp(Contender current, List<Contender> visited)
1. небезопасно получается. вы подруге можете любой список посещённых передать, и любого претендента и как угодно её обмануть
2. по условию подруга может сравнивать только претендентов, которых принцесса уже видела. не вижу этой проверки

2022-10-09 04:58 UTC, Ningyo commented on C_Sharp/Hall.cs
> +        public List<Contender> contenders = new ();
1.public? кто угодно в любой момент времени может этот список заменить извне?
2.если это правда public, то название не соответствует - публичные свойства именуются в PascalCase

2022-10-09 04:58 UTC, Ningyo commented on C_Sharp/Hall.cs
> +            using StreamReader reader = new("Names.txt");
опасно помещать сложную логику в конструктор. особенно если в будущем вы захотите загружать претендентов из бд, например, вам придётся вызывать асинхронную по природе операцию синхронно и убивать все плюшки асинхронности, т.к. асинхронного конструктора не бывает

2022-10-09 04:58 UTC, Ningyo commented on C_Sharp/Hall.cs
> +        public Contender GetContender()
просто get? это не очень соответствует происходящему внутри. по названию можно подумать, что можно любого претендента достать, а не **следующего**

2022-10-09 04:58 UTC, Ningyo commented on C_Sharp/Princess.cs
> +        bool iAmSingle = true;
приватные поля принято называть с нижнего подчёркивания
лучше явно писать доступность, чтобы не загружать мозг

2022-10-09 04:58 UTC, Ningyo commented on C_Sharp/Princess.cs
> +                happiness = contender.Score;
если принцесса может запросто узнать Score претендента, зачем ей вообще весь этот поиск? может просто ждать 100

2022-10-09 04:58 UTC, Ningyo commented on C_Sharp/Princess.cs
> +        public int FindHusband(Hall hall, Friend friend)
1. из названия не понятно, почему "найти мужа" возвращает int - что это число значит?
2. здесь и в подобных местах: не обязательно передавать в функцию холл и подругу. холл и подруга в ходе выполнения программы не меняются, они одинаковые при каждом вызове. вы можете просто при инициализации принцессы их запомнить

2022-10-09 04:58 UTC, Ningyo commented on C_Sharp/Princess.cs
> +                if (num_contenders > 36)
magic numbers. нужно вынести хотя бы в приватные константы, чтобы было понятное название и описание

2022-10-09 04:58 UTC, Ningyo commented on C_Sharp/Princess.cs
> +                    return happiness;
в чём смысл отдельной строчки с присваиванием, если вы тут же возвращаете результат?

2022-10-09 04:58 UTC, Ningyo commented on C_Sharp/Princess.cs
> +                if (num_contenders > 36)
это сишный стиль наименования. в c# используется camelCase и PascalCase. в лекциях это было, пересмотрите слайды и ссылки на код стайл, пожалуйста.

2022-10-09 04:58 UTC, Ningyo commented on C_Sharp/Hall.cs
> +            Visited.Add(next);
из названия совершенно непонятно, что внутри происходит дополнительно помещение претендента в список посещённых. похоже на не единственную ответственность. вызывает недоумение при чтении кода ниже: вот мы взяли претендента, пошли на свидание, попросили подругу сравнить...стоп? мы используем список посещённых, но ничего в него не добавляем, что за магия?

2022-10-09 04:58 UTC, Ningyo commented on C_Sharp/Program.cs
> +    file.WriteLine(contender.Name + " " + contender.Score);
т.к. немного строк соединяете, можно использовать [интерполяцию строк](https://learn.microsoft.com/en-us/dotnet/csharp/tutorials/string-interpolation) - так красивее

2022-10-09 04:58 UTC, Ningyo commented on C_Sharp/Hall.cs
> +            while((name = reader.ReadLine())!= null)
из кода никак не понятно, что претендентов будет 100, и они будут с уникальными именами

2022-10-09 04:58 UTC, Ningyo commented on C_Sharp/Princess.cs
> +                Contender contender = hall.GetContender();
можно использовать var, и так понятно, что это Contender

2022-10-09 04:58 UTC, Ningyo commented on C_Sharp/Princess.cs
> +
лишняя пустая строка, выглядит неаккуратно

2022-10-09 04:58 UTC, Ningyo commented on C_Sharp/Friend.cs
> +    class Friend
как минимум на подругу и холл хорошо бы добавить интерфейсы, чтобы было легче тестировать потом

2022-10-09 04:58 UTC, Ningyo commented on C_Sharp/Contender.cs
> +    class Contender
нигде нет саммари. полезно писать саммари к классам\интерфейсам, хотя бы к методам интерфейсов, публичным методам и полям классов

2022-10-09 04:58 UTC, Ningyo commented on C_Sharp/Hall.cs
> +            int score = 1;
по умолчанию при подобной инициализации цифровые литералы превращаются в тип int, так что тут не очень обязательно уточнять тип переменной

2022-10-09 04:58 UTC, Ningyo commented on C_Sharp/Hall.cs
> +            Contender next = contenders.First();
здесь тоже не обязательно писать тип, и так понятно

2022-10-09 13:01 UTC, CalvinLezes commented on C_Sharp/Contender.cs
> +        public int Score { get => score; set => score = value; }
Сделано

2022-10-09 13:01 UTC, CalvinLezes commented on C_Sharp/Contender.cs
> +        public string? Name { get => name; set => name = value; }
Сделано

2022-10-09 13:01 UTC, CalvinLezes commented on C_Sharp/Friend.cs
> +        public bool Cmp(Contender current, List<Contender> visited)
Сделано

2022-10-09 13:40 UTC, CalvinLezes commented on C_Sharp/Friend.cs
> +            foreach(var previous in visited)
Сделано, заменил foreach на Visited.Find(...)

2022-10-09 13:42 UTC, CalvinLezes commented on C_Sharp/Friend.cs
> +        public bool Cmp(Contender current, List<Contender> visited)
Сделано, 
Переписал так, чтобы метод сравнивал только двух претендентов
1. сделал чтобы во Friend хранился Hall, и через него получался список посещенных. 
2. Добавил проверку, что оба претендента находятся в списке тех, кого видела принцесса

2022-10-09 13:43 UTC, CalvinLezes commented on C_Sharp/Hall.cs
> +        public List<Contender> contenders = new ();
Сделано, поменял на private

2022-10-09 13:44 UTC, CalvinLezes commented on C_Sharp/Hall.cs
> +            using StreamReader reader = new("Names.txt");
Сделано, убрал конструктор, сделал отдельный метод LoadContenders, который загружает список претендентов

2022-10-09 13:44 UTC, CalvinLezes commented on C_Sharp/Hall.cs
> +        public Contender GetContender()
Сделано, переименовал в GetNextContender

2022-10-09 13:45 UTC, CalvinLezes commented on C_Sharp/Princess.cs
> +        bool iAmSingle = true;
Сделано, переименовал и добавил модификатор private

2022-10-09 13:45 UTC, CalvinLezes commented on C_Sharp/Princess.cs
> +                happiness = contender.Score;
Сделано

2022-10-09 13:47 UTC, CalvinLezes commented on C_Sharp/Princess.cs
> +        public int FindHusband(Hall hall, Friend friend)
Сделано
1. Теперь "Найти мужа" возвращает мужа
2. Добавил поля холл и подруга в принцессу

2022-10-09 13:47 UTC, CalvinLezes commented on C_Sharp/Princess.cs
> +                if (num_contenders > 36)
Сделано, добавил константу numberOfContedersToSkip

2022-10-09 13:48 UTC, CalvinLezes commented on C_Sharp/Princess.cs
> +                    return happiness;
Сделано, убрал эти строчки, перенес проверку на пустой холл в условие цикла

2022-10-09 13:49 UTC, CalvinLezes commented on C_Sharp/Princess.cs
> +                if (num_contenders > 36)
Сделано, переименовал в numContenders и перенес объявление переменной в функцию

2022-10-09 13:51 UTC, CalvinLezes commented on C_Sharp/Hall.cs
> +            Visited.Add(next);
Сделано, перенес добавление претендента в список посетивших принцессу в метод FindHusband в Princess.

2022-10-09 13:53 UTC, CalvinLezes commented on C_Sharp/Princess.cs
> +                Contender contender = hall.GetContender();
Сделано

2022-10-09 13:56 UTC, CalvinLezes commented on C_Sharp/Princess.cs
> +
Сделано

2022-10-09 13:56 UTC, CalvinLezes commented on C_Sharp/Hall.cs
> +            int score = 1;
Сделано

2022-10-09 13:56 UTC, CalvinLezes commented on C_Sharp/Hall.cs
> +            Contender next = contenders.First();
Сделано

2022-10-09 14:02 UTC, CalvinLezes commented on C_Sharp/Hall.cs
> +            while((name = reader.ReadLine())!= null)
Сделано, заменил while на for от 0 до 100

2022-10-09 14:23 UTC, CalvinLezes commented on C_Sharp/Program.cs
> +    file.WriteLine(contender.Name + " " + contender.Score);
Сделано

2022-10-09 14:41 UTC, CalvinLezes commented on C_Sharp/Friend.cs
> +    class Friend
Сделано

2022-10-09 15:15 UTC, CalvinLezes commented on C_Sharp/Contender.cs
> +    class Contender
Сделано, добавил саммари ко всем классам, полям и методам. Никогда этого не делал на самом деле, поэтому не уверен, что все правильно.

2022-10-10 12:44 UTC, Ningyo commented on C_Sharp/Contender.cs
> +        public int Score { get => score; set => score = value; }
у вас сеттеры публичные. кто угодно претенденту в процессе его жизни может заменить свойства, получается?

2022-10-10 12:48 UTC, Ningyo commented on C_Sharp/Contender.cs
> +    class Contender
"это поле"\"этот класс"\"этот метод" не обязательно писать) но оке, для тренировки пойдёт. если будет большое желание, можете убрать лишнюю воду из саммари)

2022-10-10 12:48 UTC, Ningyo commented on C_Sharp/Friend.cs
> +        public bool Cmp(Contender current, List<Contender> visited)
осталось только добавить понятности, в каком случае что возвращается. отговорка "это стандартный метод" не пойдёт, держать в голове все "стандартные методы" крайне сложно, лучше не полениться описать

2022-10-10 13:12 UTC, Ningyo commented on C_Sharp/Friend.cs
> +            if (!hall.Visited.Contains(current) || !hall.Visited.Contains(previous))
есть небольшая особенность с .Contains(current). представим, что у нас есть Иван Иванович 10. что будет, если он уже находится в Visited, и вы сделаете Visited.Contains(new Contender("Иван Иванович", 10))?

2022-10-10 13:12 UTC, Ningyo commented on C_Sharp/Friend.cs
> +        /// <summary>
здесь и в подобных местах: не хватает строки, чтобы визуально "разлепить" методы. они у вас всё ещё слеплены в сплошное полотно. это сложно читать

2022-10-10 13:12 UTC, Ningyo commented on C_Sharp/Hall.cs
> +    class Hall: IHall
у вас пробелы скачут. то Friend:IFriend то Hall: IHall. неаккуратно

2022-10-10 13:12 UTC, Ningyo commented on C_Sharp/Hall.cs
> +        public List<Contender> contenders = new ();
private вижу, именование по принятым правилам - нет. приватные поля обычно именуются с нижнего подчёркивания. попробуйте решарпер установить - он всю эту мелочь тут же подсвечивает

2022-10-10 13:12 UTC, Ningyo commented on C_Sharp/Princess.cs
> +        /// She asks a hall to give her the next contender,
весь алгоритм описывать в саммари не обязательно. лучше краткую выжимку сделать, описать ответственность метода. а внутри уже можете писать  более подробные комментарии рядом с логикой

2022-10-10 13:12 UTC, Ningyo commented on C_Sharp/Princess.cs
> +        bool iAmSingle = true;
модификаторы вижу - класс. переименований не вижу

2022-10-10 13:12 UTC, Ningyo commented on C_Sharp/Princess.cs
> +                happiness = contender.Score;
ну по сути она у вас всё ещё имеет доступ к Score. тип Сontender этого ей совсем не запрещает. представьте, что вы работаете с внешним сервисом холла, и он вам вот такого претендента возвращает, с именем и Score. ну и зачем тогда реализовывать сложную логику. как будто кто-то на той стороне проверит, смотрели вы в Score или нет

2022-10-10 13:12 UTC, Ningyo commented on C_Sharp/Program.cs
> +if(husband != null)
не хорошо, что счастье принцессы считается извне. счастье принцессы очень похоже на ответственность принцессы

2022-10-10 13:12 UTC, Ningyo commented on C_Sharp/Hall.cs
> +            while((name = reader.ReadLine())!= null)
и создали magic number) и потенциально опасную ситуацию, если строк в файле будет меньше

2022-10-10 13:12 UTC, Ningyo commented on C_Sharp/Friend.cs
> +    class Friend
1. добавили - класс. теперь нужно из использовать) в принцессе у вас по-прежнему конкретные холл и подруга
2.в идеале в интерфейсы тоже бы добавить саммари к методам. когда вы заиспользуете интерфейсы, при наведении на методы будет подсвечиваться саммари из интерфейсов (которого сейчас нет). кстати, это повод обратить внимание на формулировки в саммари - не может быть в интерфейсе описан алгоритм, по которому будет работать метод. это противоречит самой сути интерфейса (вы можете менять реализацию, оставляя одинаковый контракт)

2022-10-10 15:51 UTC, CalvinLezes commented on C_Sharp/Contender.cs
> +        public int Score { get => score; set => score = value; }
Заменил set на init, это же сделает поля неизменяемыми?

2022-10-10 15:53 UTC, CalvinLezes commented on C_Sharp/Friend.cs
> +    class Friend
Написал саммари для интерфейсов, но они получились почти такие же как у классов, пока не понимаю в чем должно быть различие

2022-10-10 15:53 UTC, CalvinLezes commented on C_Sharp/Friend.cs
> +        public bool Cmp(Contender current, List<Contender> visited)
Прописал, что конкретно возвращает функция.

2022-10-10 15:54 UTC, CalvinLezes commented on C_Sharp/Friend.cs
> +        /// <summary>
Сделано

2022-10-10 15:54 UTC, CalvinLezes commented on C_Sharp/Hall.cs
> +    class Hall: IHall
Добавил пробел

2022-10-10 15:55 UTC, CalvinLezes commented on C_Sharp/Princess.cs
> +        /// She asks a hall to give her the next contender,
к первому, установил решарпер, вроде все поисправлял, что подсвечивалось
ко второму, попытался уменьшить саммари к классам и методам

2022-10-10 16:37 UTC, CalvinLezes commented on C_Sharp/Program.cs
> +if(husband != null)
Сделано, счастье принцессы считается внутри класса, сделал так, чтобы выбранный претендент хранился в холле, чтобы получить его score, ведь у принцессы нет к нему доступа.

2022-10-10 17:19 UTC, CalvinLezes commented on C_Sharp/Hall.cs
> +            while((name = reader.ReadLine())!= null)
Переписал, вынес magic number в константу

2022-10-11 07:51 UTC, Ningyo requested changes

2022-10-11 07:51 UTC, Ningyo commented on C_Sharp/Hall.cs
> +    public List<Contender> Visited { get; } = new();
сюда кто угодно может добавить элемент

2022-10-11 07:51 UTC, Ningyo commented on C_Sharp/Friend.cs
> +        private Hall hall;
_

2022-10-11 07:51 UTC, Ningyo commented on C_Sharp/Hall.cs
> +        using StreamReader reader = new("Names.txt"); //Text file with 100 unique names
комментарий в одну строку с кодом неудобно читать

2022-10-11 07:51 UTC, Ningyo commented on C_Sharp/Hall.cs
> +    public int GetHusbandScore()
можно вернуть обнуляемое

2022-10-11 07:51 UTC, Ningyo commented on C_Sharp/Princess.cs
> +            return score < 51 ? 0 : score; //If contender's score is less then 51, her happiness is 0
magic number

2022-10-11 09:47 UTC, CalvinLezes commented on C_Sharp/Princess.cs
> +                happiness = contender.Score;
Теперь принцесса получает только имя претендента

2022-10-11 09:48 UTC, CalvinLezes commented on C_Sharp/Friend.cs
> +            if (!hall.Visited.Contains(current) || !hall.Visited.Contains(previous))
Подруга теперь получает имена претендентов и ищет претендентов с соответствующими именами с помощью Find.

2022-10-11 09:49 UTC, CalvinLezes commented on C_Sharp/Hall.cs
> +    public List<Contender> Visited { get; } = new();
Перенес visited в подругу и сделал приватным. В принцессу тоже добавил список visited, но из имен претендентов.

2022-10-11 09:49 UTC, CalvinLezes commented on C_Sharp/Friend.cs
> +        private Hall hall;
Сделано

2022-10-11 09:50 UTC, CalvinLezes commented on C_Sharp/Hall.cs
> +        using StreamReader reader = new("Names.txt"); //Text file with 100 unique names
Убрал комментарии в одну строку с кодом

2022-10-11 09:51 UTC, CalvinLezes commented on C_Sharp/Hall.cs
> +    public int GetHusbandScore()
Сделано

2022-10-11 09:51 UTC, CalvinLezes commented on C_Sharp/Princess.cs
> +            return score < 51 ? 0 : score; //If contender's score is less then 51, her happiness is 0
Вынес в локальную константу

2022-10-11 09:53 UTC, CalvinLezes commented on C_Sharp/Friend.cs
> +            if (!hall.Visited.Contains(current) || !hall.Visited.Contains(previous))
Поскольку visited теперь хранится в подруге, холл при выдаче имени нового претендента принцессе передает претендента подруге чтобы она сохранила его в visited. Переименовал метод в GetNextContenderAndTellFriendAboutIt.

2022-10-11 09:53 UTC, CalvinLezes commented on C_Sharp/Hall.cs
> +    public List<Contender> Visited { get; } = new();
Поскольку visited теперь хранится в подруге, холл при выдаче имени нового претендента принцессе передает претендента подруге чтобы она сохранила его в visited. Переименовал метод в GetNextContenderAndTellFriendAboutIt.

2022-10-11 09:56 UTC, CalvinLezes commented on C_Sharp/Princess.cs
> +                happiness = contender.Score;
Добавил метод возвращения претендента в холл, если принцесса решила выйти за него замуж, холл сохраняет его в _husband, если нет, то удаляет его из списка претендентов.

2022-10-11 12:14 UTC, Ningyo commented on C_Sharp/Hall.cs
> +    public List<Contender> Visited { get; } = new();
если в названии функции появляется And - это плохой сигнал. это сигнал, что либо у вашей функции много слишком разных ответственностей, либо вы не удачно описали эту ответственность, чтобы она укладывалась в одну фразу

2022-10-11 12:16 UTC, Ningyo commented on C_Sharp/Hall.cs
> +    public int GetHusbandScore()
что вернётся в строке _husband?.Score если _husband == null ? вы уверенны, что после этого нужно делать ещё ?? null ?

2022-10-11 12:25 UTC, Ningyo commented on C_Sharp/Hall.cs
> +    public List<Contender> Visited { get; } = new();
но ладно, пусть пока побудет. этот вопрос закрываю

2022-10-11 12:27 UTC, Ningyo commented
у вас с каждым обновлением появляются какие-то пустые строки в неожиданных местах - то в конце файла, то ещё где. пройдитесь сами взглядом по коду, пожалуйста, и удалите лишнее. выглядит неаккуратно. всё равно вам ещё момент с GetHusbandScore нужно доделать

2022-10-12 06:30 UTC, CalvinLezes commented on C_Sharp/Hall.cs
> +    public int GetHusbandScore()
Сделано, не знал, что так будет работать

2022-10-12 06:30 UTC, CalvinLezes commented
> у вас с каждым обновлением появляются какие-то пустые строки в неожиданных местах - то в конце файла, то ещё где. пройдитесь сами взглядом по коду, пожалуйста, и удалите лишнее. выглядит неаккуратно. всё равно вам ещё момент с GetHusbandScore нужно доделать

Сделано

2022-10-12 07:03 UTC, CalvinLezes commented
Я немного переписал, убрал метод ReturnHusband, добавил переменную в которой хранится индекс следующего претендента, и следующий претендент достается по нему, а из списка никто не удаляется. Мне кажется так выглядит по-аккуратней, но могу вернуть как было. @Ningyo

2022-10-12 18:23 UTC, Ningyo approved these changes

2022-10-12 18:23 UTC, Ningyo commented on C_Sharp/Princess.cs
> +        public Princess(Hall hall, Friend friend)
IHall и IFriend. зависеть от абстракций - не от конкретных реализаций. переделайте хотя бы в следующей задаче

2022-10-12 18:23 UTC, merged