Task2
CalvinLezes/C_Sharp pull request #2
Opened 2022-10-17 16:49 UTC by CalvinLezes

Добавил .NET Generic Host, вынес Contender Generator в отдельный класс. Класс Princess имплементирует IHostedService, добавил функцию вывода результата в принцессу.

2022-10-20 14:20 UTC, Ningyo requested changes

2022-10-20 14:20 UTC, Ningyo commented on C_Sharp/Princess.cs
> +        /// Print result offinding husband
пробел потеряли)

2022-10-20 14:20 UTC, Ningyo commented on C_Sharp/Princess.cs
> +            file.WriteLine("Princess had " + _namesOfVisited.Count + " dates:");
интерполяцию строк можно задействовать) красивее будет

2022-10-20 14:20 UTC, Ningyo commented on C_Sharp/Princess.cs
> +        public Princess(Hall hall, Friend friend, IHostApplicationLifetime lifeTime)
в прошлой задаче просила переделать на зависимость от абстракций) у вас даже есть в коде IHall и IFriend

2022-10-21 12:18 UTC, CalvinLezes commented on C_Sharp/Princess.cs
> +        /// Print result offinding husband
Не понял какой пробел потерял, но заметил, что этот метод не используется и убрал его

2022-10-21 12:18 UTC, CalvinLezes commented on C_Sharp/Princess.cs
> +            file.WriteLine("Princess had " + _namesOfVisited.Count + " dates:");
Использовал

2022-10-21 12:19 UTC, CalvinLezes commented on C_Sharp/Princess.cs
> +        public Princess(Hall hall, Friend friend, IHostApplicationLifetime lifeTime)
Я только сейчас понял что вы просили, заменил Hall и Friend на IHall и IFriend.

2022-10-23 08:36 UTC, Ningyo commented on C_Sharp/Princess.cs
> +        /// Print result offinding husband
оке) у вас было написано offinding в саммари (полагаю, вы имели в виду of finding)

2022-10-25 08:13 UTC, merged