Task3
CalvinLezes/C_Sharp pull request #3
Opened 2022-11-13 09:19 UTC by CalvinLezes

2022-11-15 08:28 UTC, Ningyo requested changes

2022-11-15 08:28 UTC, Ningyo commented on C_Sharp.Tests/ContenderGeneratorTest.cs
> +    public class ContenderGeneratorTest
хорошо бы добавить проверки на кол-во

2022-11-15 08:28 UTC, Ningyo commented on C_Sharp.Tests/ContenderGeneratorTest.cs
> +            var contenderNames = new List<string>();
можно сделать select

2022-11-15 08:28 UTC, Ningyo commented on C_Sharp.Tests/FriendTest.cs
> +            var friend = new Friend();
можно вынести в SetUp(поискать аналог для xunit)

2022-11-15 08:28 UTC, Ningyo commented on C_Sharp.Tests/FriendTest.cs
> +                Name="Ivan",
пробелов не хватает

2022-11-15 08:28 UTC, Ningyo commented on C_Sharp.Tests/FriendTest.cs
> +    public class FriendTest
можно добавить проверку "один был, один не был"

2022-11-15 08:28 UTC, Ningyo commented on C_Sharp.Tests/FriendTest.cs
> +            act.Should().Throw<Exception>().WithMessage("Trying to compare contenders, who princess didn't meet yet");
строку можно добавить в [ресурсы](https://learn.microsoft.com/en-us/visualstudio/ide/managing-application-resources-dotnet?view=vs-2022)

2022-11-15 08:28 UTC, Ningyo commented on C_Sharp.Tests/HallTest.cs
> +        public void GetNextContenderName_Returns_CorrectName()
что подразумеваете по "корректностью" имени?)

2022-11-15 08:28 UTC, Ningyo commented on C_Sharp.Tests/HallTest.cs
> +            for(int i = 1; i < NumberOfContenders+1; i++)
то есть, то нет пробелы

2022-11-15 08:28 UTC, Ningyo commented on C_Sharp.Tests/HallTest.cs
> +        [Fact]
не хватает пустой строки, слиплись функции

2022-11-15 08:28 UTC, Ningyo commented on C_Sharp.Tests/HallTest.cs
> +            var contenders = CreateContendersList();
не обязательно создавать 100, чтобы проверить одного

2022-11-15 08:28 UTC, Ningyo commented on C_Sharp.Tests/HallTest.cs
> +    public class HallTest
можно добавить тест на попытку взять следующего претендента, когда все закончились

2022-11-15 08:28 UTC, Ningyo commented on C_Sharp.Tests/PrincessTest.cs
> +        public void Princess_WhenChoseAHusbandWithscoreMoreThen50_HasHappinesScoreEqualToHisScore()
With**s**core

2022-11-15 08:28 UTC, Ningyo commented on C_Sharp/Hall.cs
> +        return _nextContenderIndex == NumberOfContenders|| _contenders.Count==0;
пробел пропустили перед ||

2022-11-15 15:47 UTC, CalvinLezes commented on C_Sharp.Tests/ContenderGeneratorTest.cs
> +    public class ContenderGeneratorTest
добавил тест CreateContendersList_Generates_Exactly100Contenders

2022-11-15 15:48 UTC, CalvinLezes commented on C_Sharp.Tests/FriendTest.cs
> +    public class FriendTest
добавил тест CompareContenders_OneFromVisitedOneNotFromVisited_ThrowsException

2022-11-15 15:49 UTC, CalvinLezes commented on C_Sharp.Tests/HallTest.cs
> +    public class HallTest
добавил тест GetNextContenderName_WhenHallOutOfContenders_ThrowsException

2022-11-15 15:50 UTC, CalvinLezes commented on C_Sharp.Tests/HallTest.cs
> +        public void GetNextContenderName_Returns_CorrectName()
переименовал в GetNextContenderName_Returns_NextContenderName

2022-11-15 15:51 UTC, CalvinLezes commented on C_Sharp.Tests/HallTest.cs
> +        [Fact]
добавил пустую строку

2022-11-15 15:52 UTC, CalvinLezes commented on C_Sharp/Hall.cs
> +        return _nextContenderIndex == NumberOfContenders|| _contenders.Count==0;
Добавил пробел

2022-11-15 15:53 UTC, CalvinLezes commented on C_Sharp.Tests/HallTest.cs
> +            var contenders = CreateContendersList();
Сделал, так чтобы создавался список из 1 претендента

2022-11-15 15:54 UTC, CalvinLezes commented on C_Sharp.Tests/FriendTest.cs
> +            act.Should().Throw<Exception>().WithMessage("Trying to compare contenders, who princess didn't meet yet");
добавил строки в ресурсы

2022-11-15 15:55 UTC, CalvinLezes commented on C_Sharp.Tests/FriendTest.cs
> +            var friend = new Friend();
Нашел, что аналог SetUp для xunit это просто конструктор, добавил во все тесты

2022-11-15 15:56 UTC, CalvinLezes commented on C_Sharp.Tests/FriendTest.cs
> +                Name="Ivan",
Добавил

2022-11-15 15:56 UTC, CalvinLezes commented on C_Sharp.Tests/ContenderGeneratorTest.cs
> +            var contenderNames = new List<string>();
Сделал селект

2022-11-15 15:57 UTC, CalvinLezes commented on C_Sharp.Tests/HallTest.cs
> +            for(int i = 1; i < NumberOfContenders+1; i++)
Исправлено

2022-11-15 16:05 UTC, CalvinLezes commented on C_Sharp.Tests/PrincessTest.cs
> +        public void Princess_WhenChoseAHusbandWithscoreMoreThen50_HasHappinesScoreEqualToHisScore()
Исправлено

2022-11-20 06:08 UTC, Ningyo commented on C_Sharp.Tests/ContenderGeneratorTest.cs
> +            _contenderList = contenderGeneator.CreateContendersList();
м вы вынесли зачем-то генерацию в конструктор, и теперь у вас все тесты этого класса смотрят на одни и те же данные. в вашем конкретном случае ничего страшного, но вообще не стоит делать тесты зависимыми друг от друга по данным. вы не управляете порядком выполнения тестов, и такие зависимости могут превратиться в огромную боль, если данные как-то меняются в тестах

2022-11-20 06:08 UTC, Ningyo commented on C_Sharp.Tests/ContenderGeneratorTest.cs
> +            _contenderList = contenderGeneator.CreateContendersList();
upd: кажется, поняла, что вы так сделали из-за xunit и отсутствия сетапов. можете это не переделывать, но хотелось бы, чтобы просто приняли во внимание. здесь и в похожих местах

2022-11-20 06:08 UTC, Ningyo commented on C_Sharp.Tests/FriendTest.cs
> +
лишняя пустая строка

2022-11-20 06:08 UTC, Ningyo commented on C_Sharp.Tests/FriendTest.cs
> +            var friend = new Friend();
ааа блин) сейчас быстренько загуглила, пишут, что создатель xunit верит, что сетапы - зло, поэтому их в принципе нет. конструктор всё же отличается от сетапа - он выполняется один раз для создания экземпляра класса. а сетап выполняется перед каждым тестом. и это большая разница. у вас тесты в подруге корректно выполняются? вы пробовали дебажить? просто вижу, что тут, в отличие от тестов генератора, состояние подруги меняется в тестах, и это может аффектить на другие тесты в этом классе

2022-11-20 06:13 UTC, Ningyo commented on C_Sharp.Tests/HallTest.cs
> +    public class HallTest
класс) только я теперь что-то не очень понимаю, в чем разница между вашими тестами "когда все закончились" и "когда пустой холл" - у вас же теперь холл для всех тестов одинаковый с одним претендентом в нём. что тогда проверяет "пустой холл"? я думала, пустой холл - это когда изначально никого в нём не было? или я не так вас поняла?

2022-11-20 06:50 UTC, CalvinLezes commented on C_Sharp.Tests/HallTest.cs
> +    public class HallTest
Вы правильно поняли. В тесте "Когда пустой холл" нет строчки` _hall.CreateContendersList(); `, которая создает список претендентов в холле.

2022-11-20 08:30 UTC, Ningyo commented on C_Sharp.Tests/HallTest.cs
> +    public class HallTest
но у вас же один и тот же холл во всех тестах? а CreateContendersList в других тестах вызывается. получается, в тесте на пустой холл он может быть на самом деле не пуст? вы это проверяли?

2022-11-21 06:59 UTC, CalvinLezes commented on C_Sharp.Tests/FriendTest.cs
> +            var friend = new Friend();
Я попробовал подебажить. В начале каждого теста у подруги пустой список визитед, и конструктор запускается перед каждым тестом.

2022-11-21 07:05 UTC, CalvinLezes commented on C_Sharp.Tests/HallTest.cs
> +    public class HallTest
проверил, холл пуст в начале теста, конструктор запускается перед каждым тестом.

2022-11-21 07:06 UTC, CalvinLezes commented on C_Sharp.Tests/FriendTest.cs
> +
убрал

2022-11-21 07:09 UTC, CalvinLezes commented on C_Sharp.Tests/FriendTest.cs
> +            var friend = new Friend();
На сайте xunit написано: "xUnit.net creates a new instance of the test class for every test that is run, so any code which is placed into the constructor of the test class will be run for every single test. This makes the constructor a convenient place to put reusable context setup code where you want to share the code without sharing object instances (meaning, you get a clean copy of the context object(s) for every test that is run)."

2022-11-22 08:23 UTC, merged